IDLE_TIME: 240

MOTD_DEFAULT: Bityard

MOTD_X_MIN: -341
MOTD_Y_MIN: 85
MOTD_Z_MIN: 259
MOTD_X_MAX: -341
MOTD_Y_MAX: 87
MOTD_Z_MAX: 264

SPAWN_GATEWAY_X: -378
SPAWN_GATEWAY_Y: 70
SPAWN_GATEWAY_Z: 267

SPAWN_GATEWAY_EXIT_X: -378
SPAWN_GATEWAY_EXIT_Y: 70
SPAWN_GATEWAY_EXIT_Z: 267

RETURN_GATEWAY_X: -6225
RETURN_GATEWAY_Y: 73
RETURN_GATEWAY_Z: 1099